spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dksekdms3710@gmail.com
    password: ar^^1930sm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true